name: FDN
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 42
use_ratio: true

datasets:
  train:
    name: lolblur-train
    type: PairedImageDataset
    dataroot_gt: /data/tuluwei/dataset/lolblur/train/high_sharp/*/*
    dataroot_lq: /data/tuluwei/dataset/lolblur/train/low_blur/*/*

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 128
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: lolblur-test
    type: PairedImageDataset
    dataroot_gt: /data/tuluwei/dataset/lolblur/test/high_sharp/*/*
    dataroot_lq: /data/tuluwei/dataset/lolblur/test/low_blur/*/*
    io_backend:
      type: lmdb

  val_tiny:
    name: lolblur-test
    type: PairedImageDataset
    dataroot_gt: /data/tuluwei/dataset/lolblur_test_tiny2/high_sharp/*/*
    dataroot_lq: /data/tuluwei/dataset/lolblur_test_tiny2/low_blur/*/*
    io_backend:
      type: lmdb


network_g:
  type: FDN


# path
path:
  pretrain_network_g:
  strict_load_g:
  resume_state:

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 500000
    eta_min: !!float 1e-7

  total_iter: 500000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0  
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
